
name: BetterJoy-CI

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:

  build_BetterJoy:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 下载代码
    - name: checkout source code
      shell: cmd
      run: |
        git clone --depth 1 -b master --single-branch https://github.com/Davidobot/BetterJoy.git betterjoy
        cd betterjoy
        git apply --ignore-space-change --ignore-whitespace --whitespace=nowarn ../betterjoy.patch
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/4.6.1/4.7.2/" BetterJoyForCemu/BetterJoy.csproj
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.conCntrls.Text = .*/this.conCntrls.Text = \"已连接的控制器\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.loc1.Text = .*/this.loc1.Text = \"定位\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.loc2.Text = .*/this.loc2.Text = \"定位\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.loc3.Text = .*/this.loc3.Text = \"定位\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.loc4.Text = .*/this.loc4.Text = \"定位\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.passiveScanBox.Text = .*/this.passiveScanBox.Text = \"被动扫描\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.donationLink.Text = .*/this.donationLink.Text = \"打赏\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.startInTrayBox.Text = .*/this.startInTrayBox.Text = \"托盘启动\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.btn_open3rdP.Text = .*/this.btn_open3rdP.Text = \"添加控制器\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.groupBox1.Text = .*/this.groupBox1.Text = \"配置\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.settingsApply.Text = .*/this.settingsApply.Text = \"应用\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.AutoCalibrate.Text = .*/this.AutoCalibrate.Text = \"校准\";/" BetterJoyForCemu/MainForm.Designer.cs
        "C:\Program Files\Git\usr\bin\sed.exe" -i "s/this.btn_reassign_open.Text = .*/this.btn_reassign_open.Text = \"映射按键\";/" BetterJoyForCemu/MainForm.Designer.cs

    # 安装 .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202

    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    # 安装 NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'

    # 还原 NuGet 包
    - name: NuGet restore
      run: |
        cd betterjoy
        nuget restore

    # 编译整个项目
    - name: Build the solution
      run: |
        cd betterjoy
        msbuild .\BetterJoy.sln -p:Configuration=Release -p:Platform=x64 -t:Rebuild

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: BetterJoyForCemu
        path: betterjoy/BetterJoyForCemu/bin/x64/Release
