
name: DB-CI

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:

  build_db:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # openssl版本
    - name: checkout openssl version
      shell: cmd
      run: |
        openssl version

    # 下载代码
    - name: checkout source code
      shell: cmd
      run: |
        git clone --depth 1 -b windows --single-branch https://notabug.org/doublesine/navicat-keygen.git workdir

    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    # 添加 vcpkg
    #    .\vcpkg\vcpkg install openssl:x64-windows-static
    #    .\vcpkg\vcpkg install fmt:x64-windows-static
    #    .\vcpkg\vcpkg install rapidjson:x64-windows-static
    #    .\vcpkg\vcpkg install keystone:x64-windows-static
    #    .\vcpkg\vcpkg install unicorn:x64-windows-static
    - name: Setup vcpkg
      run: |
        git clone --depth 1 https://github.com/microsoft/vcpkg vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        echo '{ "name": "dbkg", "version-string": "1.0.0", "dependencies": [ "openssl", "fmt", "rapidjson", "keystone", "unicorn" ], "builtin-baseline": "2ac61f87f69f0484b8044f95ab274038fbaf7bdd", "overrides": [ { "name": "openssl", "version-string": "1.1.1n" } ] }' > vcpkg.json
        .\vcpkg\vcpkg install
        .\vcpkg\vcpkg integrate install

    # 编译整个项目
    - name: Build the solution
      run: |
        cd workdir
        msbuild .\navicat-keygen.sln -p:Configuration=Release -p:Platform=x64 -t:Rebuild

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: navicat-kg
        path: workdir/bin
